//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the sentry_chassis_controller package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __sentry_chassis_controller__CHASSISOPSCONFIG_H__
#define __sentry_chassis_controller__CHASSISOPSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace sentry_chassis_controller
{
  class ChassisOpsConfigStatics;

  class ChassisOpsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(ChassisOpsConfig &config, const ChassisOpsConfig &max, const ChassisOpsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ChassisOpsConfig &config1, const ChassisOpsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ChassisOpsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ChassisOpsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ChassisOpsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ChassisOpsConfig &config) const = 0;
      virtual void getValue(const ChassisOpsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ChassisOpsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ChassisOpsConfig::* field;

      virtual void clamp(ChassisOpsConfig &config, const ChassisOpsConfig &max, const ChassisOpsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ChassisOpsConfig &config1, const ChassisOpsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ChassisOpsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ChassisOpsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ChassisOpsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ChassisOpsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ChassisOpsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ChassisOpsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ChassisOpsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ChassisOpsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ChassisOpsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("lf_steer_p"==(*_i)->name){lf_steer_p = boost::any_cast<double>(val);}
        if("lf_steer_i"==(*_i)->name){lf_steer_i = boost::any_cast<double>(val);}
        if("lf_steer_d"==(*_i)->name){lf_steer_d = boost::any_cast<double>(val);}
        if("rf_steer_p"==(*_i)->name){rf_steer_p = boost::any_cast<double>(val);}
        if("rf_steer_i"==(*_i)->name){rf_steer_i = boost::any_cast<double>(val);}
        if("rf_steer_d"==(*_i)->name){rf_steer_d = boost::any_cast<double>(val);}
        if("lb_steer_p"==(*_i)->name){lb_steer_p = boost::any_cast<double>(val);}
        if("lb_steer_i"==(*_i)->name){lb_steer_i = boost::any_cast<double>(val);}
        if("lb_steer_d"==(*_i)->name){lb_steer_d = boost::any_cast<double>(val);}
        if("rb_steer_p"==(*_i)->name){rb_steer_p = boost::any_cast<double>(val);}
        if("rb_steer_i"==(*_i)->name){rb_steer_i = boost::any_cast<double>(val);}
        if("rb_steer_d"==(*_i)->name){rb_steer_d = boost::any_cast<double>(val);}
        if("lf_wheel_p"==(*_i)->name){lf_wheel_p = boost::any_cast<double>(val);}
        if("lf_wheel_i"==(*_i)->name){lf_wheel_i = boost::any_cast<double>(val);}
        if("lf_wheel_d"==(*_i)->name){lf_wheel_d = boost::any_cast<double>(val);}
        if("lf_wheel_max"==(*_i)->name){lf_wheel_max = boost::any_cast<double>(val);}
        if("rf_wheel_p"==(*_i)->name){rf_wheel_p = boost::any_cast<double>(val);}
        if("rf_wheel_i"==(*_i)->name){rf_wheel_i = boost::any_cast<double>(val);}
        if("rf_wheel_d"==(*_i)->name){rf_wheel_d = boost::any_cast<double>(val);}
        if("rf_wheel_max"==(*_i)->name){rf_wheel_max = boost::any_cast<double>(val);}
        if("lb_wheel_p"==(*_i)->name){lb_wheel_p = boost::any_cast<double>(val);}
        if("lb_wheel_i"==(*_i)->name){lb_wheel_i = boost::any_cast<double>(val);}
        if("lb_wheel_d"==(*_i)->name){lb_wheel_d = boost::any_cast<double>(val);}
        if("lb_wheel_max"==(*_i)->name){lb_wheel_max = boost::any_cast<double>(val);}
        if("rb_wheel_p"==(*_i)->name){rb_wheel_p = boost::any_cast<double>(val);}
        if("rb_wheel_i"==(*_i)->name){rb_wheel_i = boost::any_cast<double>(val);}
        if("rb_wheel_d"==(*_i)->name){rb_wheel_d = boost::any_cast<double>(val);}
        if("rb_wheel_max"==(*_i)->name){rb_wheel_max = boost::any_cast<double>(val);}
        if("wheel_track"==(*_i)->name){wheel_track = boost::any_cast<double>(val);}
        if("wheel_base"==(*_i)->name){wheel_base = boost::any_cast<double>(val);}
        if("offset_lf"==(*_i)->name){offset_lf = boost::any_cast<double>(val);}
        if("offset_rf"==(*_i)->name){offset_rf = boost::any_cast<double>(val);}
        if("offset_lb"==(*_i)->name){offset_lb = boost::any_cast<double>(val);}
        if("offset_rb"==(*_i)->name){offset_rb = boost::any_cast<double>(val);}
        if("spin_vw"==(*_i)->name){spin_vw = boost::any_cast<double>(val);}
        if("use_world_frame"==(*_i)->name){use_world_frame = boost::any_cast<bool>(val);}
        if("acc_linear"==(*_i)->name){acc_linear = boost::any_cast<double>(val);}
        if("acc_angular"==(*_i)->name){acc_angular = boost::any_cast<double>(val);}
      }
    }

    double lf_steer_p;
double lf_steer_i;
double lf_steer_d;
double rf_steer_p;
double rf_steer_i;
double rf_steer_d;
double lb_steer_p;
double lb_steer_i;
double lb_steer_d;
double rb_steer_p;
double rb_steer_i;
double rb_steer_d;
double lf_wheel_p;
double lf_wheel_i;
double lf_wheel_d;
double lf_wheel_max;
double rf_wheel_p;
double rf_wheel_i;
double rf_wheel_d;
double rf_wheel_max;
double lb_wheel_p;
double lb_wheel_i;
double lb_wheel_d;
double lb_wheel_max;
double rb_wheel_p;
double rb_wheel_i;
double rb_wheel_d;
double rb_wheel_max;
double wheel_track;
double wheel_base;
double offset_lf;
double offset_rf;
double offset_lb;
double offset_rb;
double spin_vw;
bool use_world_frame;
double acc_linear;
double acc_angular;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lf_steer_p;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lf_steer_i;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lf_steer_d;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rf_steer_p;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rf_steer_i;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rf_steer_d;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lb_steer_p;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lb_steer_i;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lb_steer_d;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rb_steer_p;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rb_steer_i;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rb_steer_d;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lf_wheel_p;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lf_wheel_i;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lf_wheel_d;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lf_wheel_max;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rf_wheel_p;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rf_wheel_i;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rf_wheel_d;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rf_wheel_max;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lb_wheel_p;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lb_wheel_i;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lb_wheel_d;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lb_wheel_max;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rb_wheel_p;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rb_wheel_i;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rb_wheel_d;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rb_wheel_max;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_track;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_base;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double offset_lf;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double offset_rf;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double offset_lb;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double offset_rb;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double spin_vw;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_world_frame;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double acc_linear;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double acc_angular;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ChassisOpsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ChassisOpsConfig &__max__ = __getMax__();
      const ChassisOpsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ChassisOpsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ChassisOpsConfig &__getDefault__();
    static const ChassisOpsConfig &__getMax__();
    static const ChassisOpsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ChassisOpsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ChassisOpsConfig::ParamDescription<std::string>::clamp(ChassisOpsConfig &config, const ChassisOpsConfig &max, const ChassisOpsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ChassisOpsConfigStatics
  {
    friend class ChassisOpsConfig;

    ChassisOpsConfigStatics()
    {
ChassisOpsConfig::GroupDescription<ChassisOpsConfig::DEFAULT, ChassisOpsConfig> Default("Default", "", 0, 0, true, &ChassisOpsConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lf_steer_p = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lf_steer_p = 1000.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lf_steer_p = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_steer_p", "double", 0, "LF Steer P", "", &ChassisOpsConfig::lf_steer_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_steer_p", "double", 0, "LF Steer P", "", &ChassisOpsConfig::lf_steer_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lf_steer_i = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lf_steer_i = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lf_steer_i = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_steer_i", "double", 0, "LF Steer I", "", &ChassisOpsConfig::lf_steer_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_steer_i", "double", 0, "LF Steer I", "", &ChassisOpsConfig::lf_steer_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lf_steer_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lf_steer_d = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lf_steer_d = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_steer_d", "double", 0, "LF Steer D", "", &ChassisOpsConfig::lf_steer_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_steer_d", "double", 0, "LF Steer D", "", &ChassisOpsConfig::lf_steer_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rf_steer_p = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rf_steer_p = 1000.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rf_steer_p = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_steer_p", "double", 0, "RF Steer P", "", &ChassisOpsConfig::rf_steer_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_steer_p", "double", 0, "RF Steer P", "", &ChassisOpsConfig::rf_steer_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rf_steer_i = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rf_steer_i = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rf_steer_i = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_steer_i", "double", 0, "RF Steer I", "", &ChassisOpsConfig::rf_steer_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_steer_i", "double", 0, "RF Steer I", "", &ChassisOpsConfig::rf_steer_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rf_steer_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rf_steer_d = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rf_steer_d = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_steer_d", "double", 0, "RF Steer D", "", &ChassisOpsConfig::rf_steer_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_steer_d", "double", 0, "RF Steer D", "", &ChassisOpsConfig::rf_steer_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lb_steer_p = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lb_steer_p = 1000.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lb_steer_p = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_steer_p", "double", 0, "LB Steer P", "", &ChassisOpsConfig::lb_steer_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_steer_p", "double", 0, "LB Steer P", "", &ChassisOpsConfig::lb_steer_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lb_steer_i = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lb_steer_i = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lb_steer_i = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_steer_i", "double", 0, "LB Steer I", "", &ChassisOpsConfig::lb_steer_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_steer_i", "double", 0, "LB Steer I", "", &ChassisOpsConfig::lb_steer_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lb_steer_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lb_steer_d = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lb_steer_d = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_steer_d", "double", 0, "LB Steer D", "", &ChassisOpsConfig::lb_steer_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_steer_d", "double", 0, "LB Steer D", "", &ChassisOpsConfig::lb_steer_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rb_steer_p = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rb_steer_p = 1000.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rb_steer_p = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_steer_p", "double", 0, "RB Steer P", "", &ChassisOpsConfig::rb_steer_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_steer_p", "double", 0, "RB Steer P", "", &ChassisOpsConfig::rb_steer_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rb_steer_i = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rb_steer_i = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rb_steer_i = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_steer_i", "double", 0, "RB Steer I", "", &ChassisOpsConfig::rb_steer_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_steer_i", "double", 0, "RB Steer I", "", &ChassisOpsConfig::rb_steer_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rb_steer_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rb_steer_d = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rb_steer_d = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_steer_d", "double", 0, "RB Steer D", "", &ChassisOpsConfig::rb_steer_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_steer_d", "double", 0, "RB Steer D", "", &ChassisOpsConfig::rb_steer_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lf_wheel_p = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lf_wheel_p = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lf_wheel_p = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_wheel_p", "double", 0, "LF Wheel P", "", &ChassisOpsConfig::lf_wheel_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_wheel_p", "double", 0, "LF Wheel P", "", &ChassisOpsConfig::lf_wheel_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lf_wheel_i = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lf_wheel_i = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lf_wheel_i = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_wheel_i", "double", 0, "LF Wheel I", "", &ChassisOpsConfig::lf_wheel_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_wheel_i", "double", 0, "LF Wheel I", "", &ChassisOpsConfig::lf_wheel_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lf_wheel_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lf_wheel_d = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lf_wheel_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_wheel_d", "double", 0, "LF Wheel D", "", &ChassisOpsConfig::lf_wheel_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_wheel_d", "double", 0, "LF Wheel D", "", &ChassisOpsConfig::lf_wheel_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lf_wheel_max = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lf_wheel_max = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lf_wheel_max = 3.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_wheel_max", "double", 0, "LF Max Torque", "", &ChassisOpsConfig::lf_wheel_max)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lf_wheel_max", "double", 0, "LF Max Torque", "", &ChassisOpsConfig::lf_wheel_max)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rf_wheel_p = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rf_wheel_p = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rf_wheel_p = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_wheel_p", "double", 0, "RF Wheel P", "", &ChassisOpsConfig::rf_wheel_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_wheel_p", "double", 0, "RF Wheel P", "", &ChassisOpsConfig::rf_wheel_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rf_wheel_i = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rf_wheel_i = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rf_wheel_i = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_wheel_i", "double", 0, "RF Wheel I", "", &ChassisOpsConfig::rf_wheel_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_wheel_i", "double", 0, "RF Wheel I", "", &ChassisOpsConfig::rf_wheel_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rf_wheel_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rf_wheel_d = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rf_wheel_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_wheel_d", "double", 0, "RF Wheel D", "", &ChassisOpsConfig::rf_wheel_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_wheel_d", "double", 0, "RF Wheel D", "", &ChassisOpsConfig::rf_wheel_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rf_wheel_max = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rf_wheel_max = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rf_wheel_max = 3.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_wheel_max", "double", 0, "RF Max Torque", "", &ChassisOpsConfig::rf_wheel_max)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rf_wheel_max", "double", 0, "RF Max Torque", "", &ChassisOpsConfig::rf_wheel_max)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lb_wheel_p = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lb_wheel_p = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lb_wheel_p = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_wheel_p", "double", 0, "LB Wheel P", "", &ChassisOpsConfig::lb_wheel_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_wheel_p", "double", 0, "LB Wheel P", "", &ChassisOpsConfig::lb_wheel_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lb_wheel_i = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lb_wheel_i = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lb_wheel_i = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_wheel_i", "double", 0, "LB Wheel I", "", &ChassisOpsConfig::lb_wheel_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_wheel_i", "double", 0, "LB Wheel I", "", &ChassisOpsConfig::lb_wheel_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lb_wheel_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lb_wheel_d = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lb_wheel_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_wheel_d", "double", 0, "LB Wheel D", "", &ChassisOpsConfig::lb_wheel_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_wheel_d", "double", 0, "LB Wheel D", "", &ChassisOpsConfig::lb_wheel_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lb_wheel_max = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lb_wheel_max = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lb_wheel_max = 3.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_wheel_max", "double", 0, "LB Max Torque", "", &ChassisOpsConfig::lb_wheel_max)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("lb_wheel_max", "double", 0, "LB Max Torque", "", &ChassisOpsConfig::lb_wheel_max)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rb_wheel_p = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rb_wheel_p = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rb_wheel_p = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_wheel_p", "double", 0, "RB Wheel P", "", &ChassisOpsConfig::rb_wheel_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_wheel_p", "double", 0, "RB Wheel P", "", &ChassisOpsConfig::rb_wheel_p)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rb_wheel_i = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rb_wheel_i = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rb_wheel_i = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_wheel_i", "double", 0, "RB Wheel I", "", &ChassisOpsConfig::rb_wheel_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_wheel_i", "double", 0, "RB Wheel I", "", &ChassisOpsConfig::rb_wheel_i)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rb_wheel_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rb_wheel_d = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rb_wheel_d = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_wheel_d", "double", 0, "RB Wheel D", "", &ChassisOpsConfig::rb_wheel_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_wheel_d", "double", 0, "RB Wheel D", "", &ChassisOpsConfig::rb_wheel_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rb_wheel_max = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rb_wheel_max = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rb_wheel_max = 3.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_wheel_max", "double", 0, "RB Max Torque", "", &ChassisOpsConfig::rb_wheel_max)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("rb_wheel_max", "double", 0, "RB Max Torque", "", &ChassisOpsConfig::rb_wheel_max)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_track = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_track = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_track = 0.362;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("wheel_track", "double", 0, "Wheel Track", "", &ChassisOpsConfig::wheel_track)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("wheel_track", "double", 0, "Wheel Track", "", &ChassisOpsConfig::wheel_track)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_base = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_base = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_base = 0.362;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("wheel_base", "double", 0, "Wheel Base", "", &ChassisOpsConfig::wheel_base)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("wheel_base", "double", 0, "Wheel Base", "", &ChassisOpsConfig::wheel_base)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.offset_lf = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.offset_lf = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.offset_lf = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("offset_lf", "double", 0, "Offset LF", "", &ChassisOpsConfig::offset_lf)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("offset_lf", "double", 0, "Offset LF", "", &ChassisOpsConfig::offset_lf)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.offset_rf = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.offset_rf = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.offset_rf = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("offset_rf", "double", 0, "Offset RF", "", &ChassisOpsConfig::offset_rf)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("offset_rf", "double", 0, "Offset RF", "", &ChassisOpsConfig::offset_rf)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.offset_lb = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.offset_lb = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.offset_lb = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("offset_lb", "double", 0, "Offset LB", "", &ChassisOpsConfig::offset_lb)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("offset_lb", "double", 0, "Offset LB", "", &ChassisOpsConfig::offset_lb)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.offset_rb = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.offset_rb = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.offset_rb = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("offset_rb", "double", 0, "Offset RB", "", &ChassisOpsConfig::offset_rb)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("offset_rb", "double", 0, "Offset RB", "", &ChassisOpsConfig::offset_rb)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.spin_vw = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.spin_vw = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.spin_vw = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("spin_vw", "double", 0, "Spin Speed", "", &ChassisOpsConfig::spin_vw)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("spin_vw", "double", 0, "Spin Speed", "", &ChassisOpsConfig::spin_vw)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_world_frame = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_world_frame = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_world_frame = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<bool>("use_world_frame", "bool", 0, "World Frame", "", &ChassisOpsConfig::use_world_frame)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<bool>("use_world_frame", "bool", 0, "World Frame", "", &ChassisOpsConfig::use_world_frame)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.acc_linear = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.acc_linear = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.acc_linear = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("acc_linear", "double", 0, "Linear Acc (m/s^2)", "", &ChassisOpsConfig::acc_linear)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("acc_linear", "double", 0, "Linear Acc (m/s^2)", "", &ChassisOpsConfig::acc_linear)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.acc_angular = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.acc_angular = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.acc_angular = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("acc_angular", "double", 0, "Angular Acc (rad/s^2)", "", &ChassisOpsConfig::acc_angular)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ChassisOpsConfig::AbstractParamDescriptionConstPtr(new ChassisOpsConfig::ParamDescription<double>("acc_angular", "double", 0, "Angular Acc (rad/s^2)", "", &ChassisOpsConfig::acc_angular)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ChassisOpsConfig::AbstractGroupDescriptionConstPtr(new ChassisOpsConfig::GroupDescription<ChassisOpsConfig::DEFAULT, ChassisOpsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ChassisOpsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ChassisOpsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ChassisOpsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ChassisOpsConfig __max__;
    ChassisOpsConfig __min__;
    ChassisOpsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ChassisOpsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ChassisOpsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ChassisOpsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ChassisOpsConfig &ChassisOpsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ChassisOpsConfig &ChassisOpsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ChassisOpsConfig &ChassisOpsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ChassisOpsConfig::AbstractParamDescriptionConstPtr> &ChassisOpsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ChassisOpsConfig::AbstractGroupDescriptionConstPtr> &ChassisOpsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ChassisOpsConfigStatics *ChassisOpsConfig::__get_statics__()
  {
    const static ChassisOpsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ChassisOpsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __CHASSISOPSRECONFIGURATOR_H__
